### ISSUE TITLE
[keyboard_controller-3] has died!

### ISSUE THREAD

**Issue by zyzhong** [AutonomyLab/ardrone_autonomy#126]
I use Ubuntu 12.04 64 bits, and install the ros follow http://wiki.ros.org/fuerte/Installation/Ubuntu.
And I install ardrone_driver using apt-get install ros-hydro-ardrone-autonomy. Then I install ardrone_autonomy and ardrone_tutorials using rosmake -a. After I  launch the program using "roslaunch ardrone_tutorials keyboard_controller.launch"  I get the following message. 
Anyone could tell me how to fix it?

... logging to /home/imlegend/.ros/log/b0b0f6b6-75e5-11e4-bb83-d067e50a9632/roslaunch-ubuntu-3563.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ubuntu:57041/
# SUMMARY

CLEAR PARAMETERS
- /ardrone_driver/

PARAMETERS
- /ardrone_driver/altitude_max
- /ardrone_driver/altitude_min
- /ardrone_driver/control_vz_max
- /ardrone_driver/control_yaw
- /ardrone_driver/euler_angle_max
- /ardrone_driver/flight_without_shell
- /ardrone_driver/outdoor
- /rosdistro
- /rosversion

NODES
  /
    ardrone_driver (ardrone_autonomy/ardrone_driver)
    keyboard_controller (ardrone_tutorials/keyboard_controller.py)

auto-starting new master
process[master]: started with pid [3577]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to b0b0f6b6-75e5-11e4-bb83-d067e50a9632
process[rosout-1]: started with pid [3590]
started core service [/rosout]
process[ardrone_driver-2]: started with pid [3603]
Wait authentification
process[keyboard_controller-3]: started with pid [3604]
Traceback (most recent call last):
  File "/opt/ros/hydro/stacks/ardrone_tutorials/src/keyboard_controller.py", line 9, in <module>
    import roslib; roslib.load_manifest('ardrone_tutorials')
  File "/opt/ros/hydro/lib/python2.7/dist-packages/roslib/launcher.py", line 62, in load_manifest
    sys.path = _generate_python_path(package_name, _rospack) + sys.path
  File "/opt/ros/hydro/lib/python2.7/dist-packages/roslib/launcher.py", line 98, in _generate_python_path
    packages = get_depends(pkg, rospack) 
  File "/opt/ros/hydro/lib/python2.7/dist-packages/roslib/launcher.py", line 51, in get_depends
    vals = rospack.get_depends(package, implicit=True)
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 227, in get_depends
    s.update(self.get_depends(p, implicit))
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 221, in get_depends
    names = [p.name for p in self.get_manifest(name).depends]
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 159, in get_manifest
    return self._load_manifest(name)
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 198, in _load_manifest
    retval = self._manifests[name] = parse_manifest_file(self.get_path(name), self._manifest_name, rospack=self)
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 190, in get_path
    raise ResourceNotFound(name, ros_paths=self._ros_paths)
rospkg.common.ResourceNotFound: joy
ROS path [0]=/opt/ros/hydro/share/ros
ROS path [1]=/opt/ros/hydro/share
ROS path [2]=/opt/ros/hydro/stacks
================================================================================REQUIRED process [keyboard_controller-3] has died!
process has died [pid 3604, exit code 1, cmd /opt/ros/hydro/stacks/ardrone_tutorials/src/keyboard_controller.py __name:=keyboard_controller __log:=/home/imlegend/.ros/log/b0b0f6b6-75e5-11e4-bb83-d067e50a9632/keyboard_controller-3.log].
log file: /home/imlegend/.ros/log/b0b0f6b6-75e5-11e4-bb83-d067e50a9632/keyboard_controller-3*.log
# Initiating shutdown!

Wait authentification
[keyboard_controller-3] killing on exit
[ardrone_driver-2] killing on exit
Wait authentification
===================+> 192.168.1.1
Getting AR.Drone version ...
Getting AR.Drone version ...
Getting AR.Drone version ...
Getting AR.Drone version ...
Getting AR.Drone version ...
[ardrone_driver-2] escalating to SIGTERM
[ardrone_driver-2] escalating to SIGKILL
[rosout-1] killing on exit
[master] killing on exit
Shutdown errors:
- process[ardrone_driver-2, pid 3603]: required SIGKILL. May still be running.
  shutting down processing monitor...
  ... shutting down processing monitor complete
  done

**Comment by zyzhong** [comment]
The joy is missing, after install the joy using "sudo apt-get install ros-fuerte-joystick-drivers" it works!
